name: wheel_crm
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # UI Style package
  io_ui:
    path: packages/io_ui
  flutter_gen: ^5.3.2
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2

  # Navigation Components
  auto_route: ^9.2.0

  # DI (Get It)
  get_it: ^7.6.0
  injectable: ^2.1.2

  # BLoC + Provider
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  stream_transform: ^2.1.0
  provider: ^6.1.1
  rxdart: ^0.28.0

  # Remote
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1

  # Local DB
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0

  # Generated
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0

  # Localization
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  flutter_localizations:
    sdk: flutter

  # Lottie
  lottie: ^3.1.2

  # Utils
  collection: ^1.17.1
  fpdart: ^1.1.0
  convert: ^3.1.1
  intl: ^0.19.0
  copy_with_extension: ^5.0.4
  mask_text_input_formatter: ^2.8.0
  flutter_slidable: ^3.0.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_native_splash: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_gen_runner:
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.4
  slang_build_runner: ^3.31.0
  analyzer: ^6.4.1

  flutter_lints: ^4.0.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  android: true
  ios: true
  color: '#FFFFFF'
  image: 'assets/images/tire.png'

flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/

  uses-material-design: true


